config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  resources :users

  get '/forums/:name/new' => 'forum_threads#new', :as => 'new_forum_thread'
  post '/forums/:name/' => 'forum_threads#create', :as => 'create_thread'
  resources :forum_threads, param: :name, :except => :new, :except => :create

  get '/forum_threads/:name/:page_num' => 'thread_pages#show', :as => 'thread_page'

  post '/forum_threads/:name/:page_num/post' => 'posts#create', :as => 'create_post'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/forums' => 'forums#index'
  get '/forums/:name/:forum_page_num' => 'forums#show', :as => 'forum_page'
  get '/forums/new' => 'forums#new'
  post '/forums/' => 'forums#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum.rb
class Forum < ApplicationRecord
	has_many :forum_threads
	validates :name, uniqueness: true, presence: true
	def to_param
		name
	end	
end

app/models/forum_thread.rb
class ForumThread < ApplicationRecord
	belongs_to :creator, :class_name => 'User', :foreign_key => 'creator_id'
	belongs_to :forum, :class_name => 'Forum', :foreign_key => 'forum_id'
	has_many :thread_pages
	has_many :posts, through: :thread_pages

	validates :name, length: {maximum: 40}, presence: true
	validates :description, length: {maximum: 100}
	def to_param
		name
	end	
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :thread_page, :class_name => 'ThreadPage', :foreign_key => 'thread_page_id'
	belongs_to :forum_thread, :class_name => 'ForumThread', :foreign_key => 'forum_thread_id'

	validates :creator_id, :message, presence: true
end

app/models/thread_page.rb
class ThreadPage < ApplicationRecord
	belongs_to :forum_thread, :class_name => 'ForumThread', :foreign_key => 'forum_thread_id'
	has_many :posts
	
	def to_param
		page_num
	end
end

app/models/user.rb
class User < ApplicationRecord
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	has_secure_password
	has_many :forumThreads

	validates :name, :email, presence: true, uniqueness: true
	validates :email, format: { with: VALID_EMAIL_REGEX } 
	validates :password, presence: true, length: {minimum: 8}

	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
	def index
		@forum_threads = ForumThread.all
	end

	def show
		@forum_thread = ForumThread.find_by_name(params[:name])
	end

	def new
		@forum_thread = ForumThread.new
	end

	def create
		@forum_thread = ForumThread.new(forum_thread_params)
		@creator = current_user
		@forum = Forum.find_by_name(params[:name])

		@forum_thread.creator_id = @creator.id
		@forum_thread.creator_name = @creator.name
		@forum_thread.forum_id = @forum.id

		if @forum_thread.save 
			# This code needs to be looked at and made cleaner.
			@initial_page = ThreadPage.new
			@initial_page.forum_thread_id = @forum_thread.id
			@initial_page.page_num = 1
			@initial_page.save

			redirect_to forum_page_path(@forum, 1)
		else
			render 'new'
		end		
	end

	def destroy

	end

	private
		def forum_thread_params
			params.require(:forum_thread).permit(:name, :description)
		end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
	include Pagination

	def index
		@forums = Forum.all
	end

	def show
		# Prevents sql injections in order command
		@forum = Forum.find_by_name(params[:name])

		sanitized_order = ForumThread.send(:sanitize_sql_for_order, params[:sort_by])
		@forum_threads = @forum.forum_threads.order(sanitized_order).all
		@page_size = 10
		@current_page = params[:forum_page_num].to_i

		#fastnar i en loop när inga threads finns!
		@wanted_threads = get_page_content(@forum_threads, @page_size, @current_page)
		@page_count = divide_pages(@forum_threads, @page_size)

		if @current_page < 1 || @current_page > @page_count
			redirect_to forum_page_path(@forum, 1)
		end
	end

	def new
		@forum = Forum.new
	end

	def create
		@forum = Forum.new(forum_params)

		if @forum.save
			redirect_to forums_path
		else
			render 'new'
		end	
	end

	private
		def forum_params
			params.require(:forum).permit(:name, :description)
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@user = User.new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def create
		@thread = ForumThread.find_by_name(params[:name])
		@latest_page = @thread.thread_pages.last
		@current_user = current_user

		@post = Post.new(post_params)

		@post.creator_id = @current_user.id
		@post.creator_name = @current_user.name
		@post.thread_page_id = @latest_page.id
		@post.forum_thread_id = @thread.id

		if @post.valid?
			#if 10 posts have been created on this page, create a new page and save the new post to that page.
			if @latest_page.posts.count > 9
				new_num = @latest_page.page_num + 1

				@latest_page = ThreadPage.new
				@latest_page.page_num = new_num
				@latest_page.forum_thread_id = @thread.id

				@latest_page.save

				@post.thread_page_id = @latest_page.id

			end	
			@post.save
			puts "yey"
			#Redirects to last page.
			redirect_to thread_page_path(@thread, @latest_page.page_num)
		else
			flash[:notice] = "Invalid post."
			redirect_back(fallback_location: root_path)
			puts "ney"	
		end
	end

	private
		def post_params 
			params.require(:post).permit(:message)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		redirect_to root_path
	end

	def create
		@user = User.find_by email: params[:email]

		if @user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			redirect_back(fallback_location: root_path)
		else
			flash[:notice] = "Login failed. Wrong Email or password."
			redirect_back(fallback_location: root_path)
		end		
	end

	def destroy
		session[:user_id] = nil
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/thread_pages_controller.rb
class ThreadPagesController < ApplicationController
	def show
		@thread = ForumThread.find_by_name(params[:name])
		@thread_pages = @thread.thread_pages
		if @page = @thread_pages.find_by_page_num(params[:page_num])
			@posts = @page.posts
		else
			#unless the page exists go gack to the first page
			redirect_to thread_page_path(@thread, 1)
		end	

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		redirect_to root_path
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path
		else
			render 'new'
		end		
	end

	private
		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_threads_helper.rb
module ForumThreadsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/thread_pages_helper.rb
module ThreadPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/forum_threads/index.html.erb
<h1>Threads</h1>

<% @forum_threads.each do |thread| %>
	<table>
		<tr>
			<td>Topic: <%= thread.name %></td>
			<td>Creator: <%= thread.creator_name %></td>
			<td>posts: <%= thread.posts.count %></td>
			<td><%= link_to 'show', thread_page_path(thread, 1) %></td>
		</tr>
	</table>
<% end %>	

app/views/forum_threads/new.html.erb
<h1>Create new thread</h1>

<%= form_for :forum_thread, url: create_thread_path do |f| %>
	<% if @forum_thread.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@forum_thread.errors.count, "error") %>
				prohibited the thread from being created:
			</h2>
			<ul>
				<% @forum_thread.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>		
		</div>	
	<% end %>

	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description, :cols => "40", :rows => "10" %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/forum_threads/show.html.erb
<h1>showing Thread</h1>

<%= link_to 'back to threads', forum_threads_path %>

<h2><%= @forum_thread.name %></h2>

<p><%= @forum_thread.description %></p>
	

app/views/forums/_pages.html.erb
page <%= @current_page %> of <%= @page_count %> | 
<% if @current_page > 1 %>
	<!--request.parameters.merge keeps the old url and changes only what is specified-->
	<%= link_to 'Prev', request.parameters.merge({:forum_page_num => @current_page - 1}) %>
<% end %>	

<% (1..@page_count).each do |page| %>
	<% if page == @current_page %>
		<strong><%= page %></strong>
	<% else %>
		<%= link_to page, request.parameters.merge({:forum_page_num => page}) %>
	<% end %>	
<% end %>


<% if @current_page < @page_count %>
	<%= link_to 'Next', request.parameters.merge({:forum_page_num => @current_page + 1 }) %>
<% end %>
|

app/views/forums/_sort.html.erb
sort with:
<% if params[:sort_by] == nil || params[:sort_by] == 'created_at ASC' %>
	<strong>time created Ascending</strong> | 
<% else %>
	<%= link_to 'time created Ascending', request.query_parameters.merge({:sort_by => 'created_at ASC'}) %>
<% end %>	
<% if params[:sort_by] == 'created_at DESC' %>
	<strong>time created Descending</strong>
<% else %>
	<%= link_to 'time created Descending', request.query_parameters.merge({:sort_by => 'created_at DESC'}) %>
<% end %>

app/views/forums/index.html.erb
<!--EXTREMELY PLACEHOLDER-->
<% if current_user && current_user.name == "Lowe" %>
	<%= link_to 'create new subforum', forums_new_path %>
<% end %>

<div id="forumsListArea">
	<% @forums.each do |forum| %>
		<div class="forum">
			<div class="forumHeader">
			<%= link_to forum.name, forum_page_path(forum, 1) %>
			</div>
			<div class="forumInfo">
				<%= forum.description %>
				<small class="info">Threads: <%= forum.forum_threads.count %></small>
			</div>
		</div>	
	<% end %>	
</div>

app/views/forums/new.html.erb
<h1>Create new subforum</h1>
<% if current_user %>
	<%= form_for :forum, url: forums_path do |f| %>
		<% if @forum.errors.any? %>
			<div id="error_explanation">
				<h2>
					<%= pluralize(@forum.errors.count, "error") %>
					prohibited the forum from being created:
				</h2>
				<ul>
					<% @forum.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>		
			</div>	
		<% end %>
		
		<p>
			<%= f.label :name %><br>
			<%= f.text_field :name %>
		</p>
		<p>
			<%= f.label :description %><br>
			<%= f.text_area :description, :cols => "40", :rows => "10" %>
		</p>

		<p>
			<%= f.submit %>
		</p>
	<% end %>
<% end %>	

app/views/forums/show.html.erb
<%= link_to 'Back', forums_path %>

<% if current_user %>
	<h3><%= link_to 'Create new thread', new_forum_thread_path %></h3>
<% else %>
	<h2>Sign in to make a thread</h2>	
<% end %>	

<div id="description">
	<div id="descriptionInfo">
		<h1><%= @forum.name %></h1>
	</div>
	<div id="descriptionContent">
		<%= @forum.description %>
	</div>	
</div>

<div id="pageArea">
<%= render 'pages' %>
	<%= render 'sort' %>	
</div>
	
<div id="forumThreadsArea">
	<% if @wanted_threads %>
		<% @wanted_threads.each do |thread| %>
			<div class="forumThread">
				<%= link_to thread.name, thread_page_path(thread, 1) %>
				<div class="forumThreadInfo">
					Created by: <%= thread.creator_name %>
					<%= thread.created_at %>
					<span class="info">posts: <%= thread.posts.count %></span>
				</div>		
			</div>		
		<% end %>	
	<% end %>	
</div>

app/views/home/index.html.erb
<h1>Welcome to my site!</h1>
<%= link_to 'Forum', forums_path %>

app/views/thread_pages/_pageArea.html.erb
page <%= @page.page_num %> of <%= @thread_pages.count %> | 
<!--Display a back button if one page lower than current page exists-->
<% if @thread_pages.exists?(page_num: @page.page_num - 1) %>
	<%= link_to 'Prev', thread_page_path(@thread, @page.page_num - 1) %>
<% end %>

<% @thread_pages.each do |page| %>	
	<!-- @page.page_num is currently viewed page-->
	<% if page.page_num == @page.page_num %>
		<%= page.page_num %>
	<% else %>
		<%= link_to page.page_num, thread_page_path(@thread, page.page_num)%>
	<% end %>	
<% end %>		
<!--Display a Next button if one page higher than current page exists-->
<% if @thread_pages.exists?(page_num: @page.page_num + 1) %>
	<%= link_to 'Next', thread_page_path(@thread, @page.page_num + 1) %>
<% end %>

app/views/thread_pages/show.html.erb
<div id="description">
	<div id="descriptionInfo">
		<small class="info">Created by: <%= @thread.creator_name %> | Started at: <%= @thread.created_at %></small>
		<h2><%= @thread.name %></h2>

	</div>
	<div id="descriptionContent">	
		<p><%= simple_format(@thread.description) %></p>
	</div>
</div>	

<div id="pageArea">
	<%= render 'pageArea' %>
</div>

<div id="postsArea">
	<% @posts.each do |post| %>
		<div class="postInfo">
			<%= post.creator_name %>
		</div>
		<div class="postContent">
			<small class="info">Posted at: <%= post.created_at %></small>
			<!--simple_format translates formating(newlines etc) into browser-readable formating-->
		 	<p><%= simple_format(post.message) %></p>
		 </div>	
	<% end %>	
</div>

<div id="pageArea">
	<%= render 'pageArea' %>
</div>

<% if current_user %>
	<div id="createPostArea">
		<h2>Create post</h2>

		<%= form_for :post, url: create_post_path do |f| %>
			<p>
				<%= f.text_area :message, :rows => "10", style: 'width:99%;' %>
			</p>

			<p>
				<%= f.submit %>
			</p>
		<% end %>
	</div>
<% end %>

<% flash.each do |name, msg| -%>
	<%= content_tag :h2, msg, class: name %>
<% end -%>

app/views/users/new.html.erb
<h1>Register here</h1>

<%= form_for :user, url: users_path do |f| %>
	
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@user.errors.count, "error") %>
				prohibited the user from being created:
			</h2>
			<ul>
				<% @user.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>		
		</div>	
	<% end %>	

	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :email %><br>
		<%= f.text_field :email %>
	</p>
	<p>
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_Confirmation %><br>
		<%= f.password_field :password_confirmation %>
	</p>
	<p>
		<%= f.submit %>		
	</p>
<% end %>		